# Generated by Django 5.0.7 on 2024-10-01 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugArchive',
            fields=[
                ('archiveId', models.AutoField(primary_key=True, serialize=False)),
                ('drugName', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': '서버 저장 약물 아카이브',
                'verbose_name_plural': '서버 저장 약물 아카이브',
            },
        ),
        migrations.CreateModel(
            name='Clinics',
            fields=[
                ('clinicId', models.AutoField(primary_key=True, serialize=False)),
                ('recentDay', models.DateTimeField()),
                ('nextDay', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '진료기록',
                'verbose_name_plural': '진료기록',
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='MyDrugArchive',
            fields=[
                ('myArchiveId', models.AutoField(primary_key=True, serialize=False)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_drug_archives', to='clinics.drugarchive')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '처방 개별 약',
                'verbose_name_plural': '처방 개별 약',
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drugId', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('initialNumber', models.IntegerField(default=0)),
                ('time', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=50)),
                ('allow', models.BooleanField(default=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='clinics.clinics')),
                ('myDrugArchive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.mydrugarchive')),
            ],
            options={
                'verbose_name': '처방약물',
                'verbose_name_plural': '처방약물',
            },
        ),
    ]
