# Generated by Django 5.0.7 on 2024-09-04 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrfDrugArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrfClinics',
            fields=[
                ('clinicId', models.AutoField(primary_key=True, serialize=False)),
                ('recentDay', models.DateTimeField()),
                ('nextDay', models.DateTimeField()),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('clinicLatitude', models.FloatField(blank=True, null=True)),
                ('clinicLongitude', models.FloatField(blank=True, null=True)),
                ('locationLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updatedAt'],
            },
        ),
        migrations.CreateModel(
            name='DrfDrug',
            fields=[
                ('drugId', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=0)),
                ('initialNumber', models.IntegerField(default=0)),
                ('time', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=50)),
                ('allow', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='clinics.drfclinics')),
                ('drugArchive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinics.drfdrugarchive')),
            ],
        ),
    ]
