# Generated by Django 5.0.7 on 2024-09-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drfdrug',
            name='drugArchive',
        ),
        migrations.AddField(
            model_name='drfdrug',
            name='drugArchive',
            field=models.ManyToManyField(to='clinics.drfdrugarchive'),
        ),
    ]
