# Generated by Django 5.0.7 on 2024-08-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfclinics',
            name='createdAt',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='drfclinics',
            name='nextDay',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='drfclinics',
            name='recentDay',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='drfdrug',
            name='status',
            field=models.CharField(choices=[('콘서타 18mg', '콘서타 18mg'), ('콘서타 27mg', '콘서타 27mg'), ('콘서타 36mg', '콘서타 36mg'), ('메디카넷 18mg', '메디카넷 18mg'), ('페로스핀 18mg', '페로스핀 18mg')], max_length=50),
        ),
    ]
