# Generated by Django 5.0.7 on 2024-09-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfclinics',
            name='drugArchives',
            field=models.ManyToManyField(related_name='clinics', to='clinics.drfdrugarchive'),
        ),
    ]
