# Generated by Django 5.0.7 on 2024-08-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_drfclinics_createdat_alter_drfclinics_nextday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drfclinics',
            options={'ordering': ['-updatedAt']},
        ),
    ]
