# Generated by Django 5.0.7 on 2024-09-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_alter_clinics_createdat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinics',
            options={'ordering': ['-updatedAt'], 'verbose_name': '진료기록', 'verbose_name_plural': '진료기록'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': '처방약물', 'verbose_name_plural': '처방약물'},
        ),
        migrations.AlterModelOptions(
            name='drugarchive',
            options={'verbose_name': '서버 저장 약물 아카이브', 'verbose_name_plural': '서버 저장 약물 아카이브'},
        ),
        migrations.AlterModelOptions(
            name='mydrugarchive',
            options={'verbose_name': '처방 개별 약', 'verbose_name_plural': '처방 개별 약'},
        ),
    ]
