# Generated by Django 5.0.7 on 2024-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_alter_drfclinics_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfdrug',
            name='status',
            field=models.CharField(choices=[('콘서타 18mg', '콘서타 18mg'), ('콘서타 27mg', '콘서타 27mg'), ('콘서타 36mg', '콘서타 36mg'), ('폭세틴 20mg', '폭세틴 20mg'), ('메디카넷 18mg', '메디카넷 18mg'), ('페로스핀 18mg', '페로스핀 18mg')], max_length=50),
        ),
    ]
