# Generated by Django 5.0.7 on 2024-09-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0004_alter_drfdrug_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfdrug',
            name='allow',
            field=models.BooleanField(default=True),
        ),
    ]
