# Generated by Django 5.0.7 on 2024-09-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_drfdrug_initialnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfclinics',
            name='clinicLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drfclinics',
            name='clinicLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drfclinics',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drfclinics',
            name='locationLabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
