# Generated by Django 5.0.7 on 2024-09-03 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0008_alter_drfdrug_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrfDrugArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drugName', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drfdrug',
            name='status',
        ),
        migrations.AlterField(
            model_name='drfdrug',
            name='time',
            field=models.CharField(choices=[('morning', '아침'), ('lunch', '점심'), ('evening', '저녁')], max_length=50),
        ),
        migrations.AddField(
            model_name='drfdrug',
            name='drugArchive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinics.drfdrugarchive'),
            preserve_default=False,
        ),
    ]
