# Generated by Django 5.0.7 on 2024-09-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0009_drfdrugarchive_remove_drfdrug_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfdrug',
            name='drugArchive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinics.drfdrugarchive'),
        ),
    ]
