# Generated by Django 5.0.7 on 2024-09-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0010_alter_drfdrug_drugarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfdrug',
            name='time',
            field=models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=50),
        ),
    ]
