# Generated by Django 5.0.7 on 2024-09-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailylog',
            options={'ordering': ['-date'], 'verbose_name': '빠른메모', 'verbose_name_plural': '빠른메모'},
        ),
    ]
