# Generated by Django 5.0.7 on 2024-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastlogs', '0002_alter_dailylog_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
