# Generated by Django 5.0.7 on 2024-07-28 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todays', to='accounts.user')),
            ],
        ),
    ]
