# Generated by Django 5.0.7 on 2024-10-01 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YearlyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('log_type', models.CharField(choices=[('dose', '약복용'), ('side_effect', '부작용')], max_length=20)),
                ('action', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '연간관리 기록',
                'verbose_name_plural': '연간관리 기록',
                'indexes': [models.Index(fields=['owner', 'date', 'log_type'], name='mypage_year_owner_i_12f2c3_idx')],
                'unique_together': {('owner', 'date', 'log_type')},
            },
        ),
    ]
