# Generated by Django 5.0.7 on 2024-09-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yearlydoselog',
            options={'verbose_name': '연간관리 - 약복용', 'verbose_name_plural': '연간관리 - 약복용'},
        ),
        migrations.AlterModelOptions(
            name='yearlysideeffectlog',
            options={'verbose_name': '연간관리 - 부작용', 'verbose_name_plural': '연간관리 - 부작용'},
        ),
    ]
