# Generated by Django 5.0.7 on 2024-11-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_post_thumbnail_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='deleted_at',
        ),
    ]
