# Generated by Django 5.0.7 on 2024-11-12 17:26

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_remove_comment_deleted_at_remove_post_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='community_p_content_d1bb77_gin'),
        ),
    ]
