# Generated by Django 5.0.7 on 2024-09-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
