# Generated by Django 5.0.7 on 2024-10-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='appleId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
