# Generated by Django 5.0.7 on 2024-09-15 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_temperature_remove_user_updatedat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('memoryId', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.JSONField(blank=True, default=list)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
