# Generated by Django 5.0.7 on 2024-09-30 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_memories_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL),
        ),
    ]
