# Generated by Django 5.0.7 on 2024-08-08 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_createdat_user_temperature_user_updatedat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='kakao_id',
            new_name='kakaoId',
        ),
    ]
