# Generated by Django 5.0.7 on 2024-09-30 16:11

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_memories_userid'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='memories',
            managers=[
                ('objects', accounts.models.SoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', accounts.models.SoftDeleteManager()),
            ],
        ),
    ]
