# Generated by Django 5.0.7 on 2024-08-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
