# Generated by Django 5.0.7 on 2024-09-15 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_memories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_product_writer',
            field=models.BooleanField(default=False),
        ),
    ]
