# Generated by Django 5.0.7 on 2024-09-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_memories_managers_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memories',
            options={'verbose_name': '챙길거리', 'verbose_name_plural': '챙길거리'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '유저관리', 'verbose_name_plural': '유저관리'},
        ),
    ]
