# Generated by Django 5.0.7 on 2024-08-09 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_id_user_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uid',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='temperature',
            field=models.FloatField(default=36.5),
        ),
    ]
