# Generated by Django 5.0.7 on 2024-09-30 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menstruation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menstruation',
            options={'verbose_name': '생리주기', 'verbose_name_plural': '생리주기'},
        ),
    ]
