# Generated by Django 5.0.7 on 2024-07-29 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drugName', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('mg', 'mg'), ('정', '정')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLog',
            fields=[
                ('clinicId', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('clinicDate', models.DateField()),
                ('nextDate', models.DateField()),
                ('doseTime', models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=10)),
                ('clinicNote', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.druglist')),
            ],
        ),
    ]
