# Generated by Django 5.0.7 on 2024-07-28 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drugName', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicLog',
            fields=[
                ('clinicId', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.TextField()),
                ('clinicDate', models.DateTimeField()),
                ('nextDate', models.DateTimeField()),
                ('doseTime', models.CharField(max_length=100)),
                ('clinicNote', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.druglist')),
            ],
        ),
    ]
