# Generated by Django 5.0.7 on 2024-07-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclog',
            name='doseTime',
            field=models.CharField(choices=[('아침', '아침'), ('점심', '점심'), ('저녁', '저녁')], max_length=10),
        ),
    ]
