# Generated by Django 5.0.7 on 2024-07-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_cliniclog_dosetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='druglist',
            name='unit',
            field=models.CharField(choices=[('mg', 'mg'), ('정', '정')], max_length=10),
        ),
    ]
