# Generated by Django 5.0.7 on 2024-07-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0003_alter_druglist_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliniclog',
            name='clinicDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cliniclog',
            name='nextDate',
            field=models.DateField(),
        ),
    ]
