# Generated by Django 5.0.7 on 2024-09-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['-updatedAt'], 'verbose_name': '개발자 공지', 'verbose_name_plural': '개발자 공지'},
        ),
    ]
