# Generated by Django 5.0.7 on 2024-07-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('하루설문', '하루설문'), ('부작용', '부작용'), ('셀프기록', '셀프기록')], max_length=10)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SymptomCare',
            fields=[
                ('symptomId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('소화기계', '소화기계'), ('정신/심리', '정신/심리'), ('신경계', '신경계'), ('심혈관계', '심혈관계'), ('생식기계', '생식기계'), ('직접입력', '직접입력')], max_length=10)),
                ('content', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ServeyLog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('today', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.questionlist')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('symptomLogId', models.AutoField(primary_key=True, serialize=False)),
                ('today', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField()),
                ('symptomQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.symptomcare')),
            ],
        ),
    ]
