# Generated by Django 5.0.7 on 2024-07-28 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('today', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QestionList',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServeyLog',
            fields=[
                ('logId', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.qestionlist')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='today.today')),
            ],
        ),
    ]
