# Generated by Django 5.0.7 on 2024-07-28 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        ('today', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCare',
            fields=[
                ('symptomId', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='QestionList',
            new_name='QuestionList',
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('symptomLogId', models.AutoField(primary_key=True, serialize=False)),
                ('answer', models.TextField()),
                ('symptomQuestions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.symptomcare')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='today.today')),
            ],
        ),
    ]
