# Generated by Django 5.0.7 on 2024-07-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_symptomcare_rename_qestionlist_questionlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='type',
            field=models.CharField(choices=[('하루설문', '하루설문'), ('부작용', '부작용'), ('셀프기록', '셀프기록')], max_length=10),
        ),
    ]
