# Generated by Django 5.0.7 on 2024-07-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_questionlist_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveylog',
            name='today',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='symptomlog',
            name='today',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
