# Generated by Django 5.0.7 on 2024-07-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_serveylog_today_alter_symptomlog_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomcare',
            name='type',
            field=models.CharField(choices=[('소화기계', '소화기계'), ('정신/심리', '정신/심리'), ('신경계', '신경계'), ('심혈관계', '심혈관계'), ('생식기계', '생식기계'), ('직접입력', '직접입력')], max_length=10),
        ),
    ]
