# Generated by Django 5.0.7 on 2024-07-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_symptomcare_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomcare',
            name='content',
            field=models.CharField(max_length=10),
        ),
    ]
