# Generated by Django 5.0.7 on 2024-08-15 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_appointment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('1', '매우 나쁨'), ('2', '나쁨'), ('3', '보통'), ('4', '좋음'), ('5', '매우 좋음')], max_length=1)),
                ('today', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='todaylogs.today')),
            ],
        ),
        migrations.CreateModel(
            name='SideEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(choices=[('1', '전혀 없음'), ('2', '거의 없음'), ('3', '조금 있음'), ('4', '꽤 있음'), ('5', '많이 있음')], max_length=1)),
                ('today', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect', to='todaylogs.today')),
            ],
        ),
        migrations.CreateModel(
            name='SelfRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('today', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='self_record', to='todaylogs.today')),
            ],
        ),
    ]
