# Generated by Django 5.0.7 on 2024-10-01 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('survey', '하루설문'), ('side_effect', '부작용설문')], max_length=20)),
                ('question_subtype', models.CharField(choices=[('depression', '우울'), ('anxiety', '불안')], max_length=20)),
            ],
            options={
                'verbose_name': '질문모음',
                'verbose_name_plural': '질문모음',
            },
        ),
        migrations.CreateModel(
            name='Today',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('next_appointment_date', models.DateField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('0', '전혀'), ('1', '며칠동안'), ('2', '7일이상'), ('3', '거의매일')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='todaylogs.question')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='todaylogs.today')),
            ],
            options={
                'verbose_name': '하루설문',
                'verbose_name_plural': '하루설문',
            },
        ),
        migrations.CreateModel(
            name='SideEffectResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', '전혀 없음'), ('2', '거의 없음'), ('3', '조금 있음'), ('4', '꽤 있음'), ('5', '많이 있음')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_responses', to='todaylogs.question')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_responses', to='todaylogs.today')),
            ],
            options={
                'verbose_name': '부작용설문',
                'verbose_name_plural': '부작용설문',
            },
        ),
        migrations.CreateModel(
            name='SelfRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_records', to='todaylogs.today')),
            ],
            options={
                'verbose_name': '셀프기록',
                'verbose_name_plural': '셀프기록',
            },
        ),
    ]
