# Generated by Django 5.0.7 on 2024-09-30 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todaylogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '질문모음', 'verbose_name_plural': '질문모음'},
        ),
        migrations.AlterModelOptions(
            name='selfrecord',
            options={'verbose_name': '셀프기록', 'verbose_name_plural': '셀프기록'},
        ),
        migrations.AlterModelOptions(
            name='sideeffectresponse',
            options={'verbose_name': '부작용설문', 'verbose_name_plural': '부작용설문'},
        ),
        migrations.AlterModelOptions(
            name='surveyresponse',
            options={'verbose_name': '하루설문', 'verbose_name_plural': '하루설문'},
        ),
    ]
