# Generated by Django 5.0.7 on 2024-08-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todaylogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('survey', 'Survey'), ('side_effect', 'Side Effect')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='survey',
            name='today',
        ),
        migrations.AlterField(
            model_name='selfrecord',
            name='today',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='self_records', to='todaylogs.today'),
        ),
        migrations.CreateModel(
            name='SideEffectResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', '전혀 없음'), ('2', '거의 없음'), ('3', '조금 있음'), ('4', '꽤 있음'), ('5', '많이 있음')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_responses', to='todaylogs.question')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='side_effect_responses', to='todaylogs.today')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('1', '매우 나쁨'), ('2', '나쁨'), ('3', '보통'), ('4', '좋음'), ('5', '매우 좋음')], max_length=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='todaylogs.question')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='todaylogs.today')),
            ],
        ),
        migrations.DeleteModel(
            name='SideEffect',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
