# Generated by Django 5.0.7 on 2024-10-01 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todaylogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('survey', 'Survey'), ('side_effect', 'Side Effect')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_sessions', to='todaylogs.today')),
            ],
        ),
    ]
