# Generated by Django 5.0.7 on 2024-10-01 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todaylogs', '0002_surveysession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_type', models.CharField(choices=[('survey', 'Survey'), ('side_effect', 'Side Effect')], max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('question_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_completions', to='todaylogs.questionsubtype')),
                ('today', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_completions', to='todaylogs.today')),
            ],
            options={
                'unique_together': {('today', 'response_type', 'question_subtype')},
            },
        ),
    ]
