# Generated by Django 5.0.7 on 2024-10-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todaylogs', '0004_mypagesideeffectcompletion_mypagesurveycompletion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mypagesurveycompletion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mypagesurveycompletion',
            name='question_subtype',
        ),
        migrations.RemoveField(
            model_name='mypagesurveycompletion',
            name='today',
        ),
        migrations.DeleteModel(
            name='MypageSideEffectCompletion',
        ),
        migrations.DeleteModel(
            name='MypageSurveyCompletion',
        ),
    ]
