# Generated by Django 5.0.7 on 2024-09-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': '개발자 건의함', 'verbose_name_plural': '개발자 건의함'},
        ),
    ]
