# Generated by Django 5.0.7 on 2024-09-30 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'ordering': ['-updatedAt'], 'verbose_name': '매거진', 'verbose_name_plural': '매거진'},
        ),
    ]
