# Generated by Django 5.0.7 on 2024-08-10 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrfProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('productPrice', models.IntegerField(default=0)),
                ('isFree', models.BooleanField(default=False)),
                ('imageUrls', models.JSONField(default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('viewCount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('sale', '판매중'), ('reservation', '예약중'), ('soldOut', '판매완료'), ('cancel', '취소')], max_length=50)),
                ('wantTradeLocation', models.JSONField(blank=True, null=True)),
                ('wantTradeLocationLabel', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryType', models.CharField(max_length=255)),
                ('likers', models.ManyToManyField(blank=True, related_name='liked_products', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
