# Generated by Django 5.0.7 on 2024-08-10 21:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drfproduct',
            old_name='image_urls',
            new_name='imageUrls',
        ),
        migrations.RemoveField(
            model_name='drfproduct',
            name='id',
        ),
        migrations.AlterField(
            model_name='drfproduct',
            name='docId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
