# Generated by Django 5.0.7 on 2024-08-15 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_drfproduct_imageurls_imagefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drfproduct',
            options={'ordering': ['-updatedAt']},
        ),
    ]
