# Generated by Django 5.0.7 on 2024-08-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_drfproduct_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drfproduct',
            name='categoryType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='drfproduct',
            name='status',
            field=models.CharField(choices=[('sale', '판매중'), ('reservation', '예약중'), ('soldOut', '판매완료'), ('cancel', '취소')], max_length=50, null=True),
        ),
    ]
